services:
  django:
    build: ./backend
    environment:
      - POSTGRES_USER=$POSTGRES_USER
      - POSTGRES_PASSWORD=$POSTGRES_PASSWORD
      - POSTGRES_DB=$POSTGRES_DB
      - REDIS_PASSWORD=$REDIS_PASSWORD
    ports:
      - 8000:8000
    volumes:
      - ./backend:/app:r
    depends_on:
      - db
      - redis

  next:
    build: ./frontend
    ports:
      - 3000:3000
    volumes:
      - ./frontend:/app:r

  db:
    image: postgres
    restart: always
    ports: 
      - 5432:5432
    environment:
      - POSTGRES_USER=$POSTGRES_USER
      - POSTGRES_PASSWORD=$POSTGRES_PASSWORD
      - POSTGRES_DB=$POSTGRES_DB
    volumes:
      - database:/var/lib/postgresql/data

  redis:
    image: redis
    restart: always
    command: redis-server --requirepass $REDIS_PASSWORD

volumes:
  database:
